### ISSUE TITLE
Shiro authentication suddently failing

### ISSUE THREAD

**Issue by gflcampos** [obiba/agate#302]
## Context
We have been using Agate/Opal/Mica for a while now but recently an error started occurring in Agate that prevents the users from logging into Agate (and, consequently, into Opal and Mica).

## Expected Behavior
Users are able to log into Agate.

## Current Behavior
I get 'Authentication failed' when trying to log into Agate.

## Detailed Description
If I try to log into Agate (v1.3.0 or v1.4.1) with a wrong password I get a 403 (which is obviously expected). But if I try to log in with the correct password, I get a 500 with the message `There is no session with id [429384f7-bab0-4448-965d-c9e6519fc571]`.  
Which means that Agate knows the password is correct and yet it can't authenticate the user.

Looking in `agate.log`, I found the error below:
```
2018-12-12 17:55:49.674 ERROR 63 --- [tp1773944868-41] o.o.s.web.filter.AuthenticationFilter    : Exception 

org.apache.shiro.session.UnknownSessionException: There is no session with id [f00ec4a1-2988-43ba-af7b-056c1886b506]
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.eis.CachingSessionDAO.readSession(CachingSessionDAO.java:261) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.setAttribute(AbstractNativeSessionManager.java:256) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.mgt.DelegatingSession.setAttribute(DelegatingSession.java:151) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.session.ProxiedSession.setAttribute(ProxiedSession.java:128) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSubjectDAO.mergePrincipals(DefaultSubjectDAO.java:205) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSubjectDAO.saveToSession(DefaultSubjectDAO.java:166) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSubjectDAO.save(DefaultSubjectDAO.java:147) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSecurityManager.save(DefaultSecurityManager.java:383) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:350) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:183) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:283) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256) ~[shiro-core-1.3.3-obiba.jar:1.3.3-obiba]
	at org.obiba.shiro.web.filter.AbstractAuthenticationExecutor.login(AbstractAuthenticationExecutor.java:33) ~[obiba-shiro-web-1.8.8.jar:na]
	at org.obiba.shiro.web.filter.AuthenticationFilter.authenticateBasicHeader(AuthenticationFilter.java:220) ~[obiba-shiro-web-1.8.8.jar:na]
	at org.obiba.shiro.web.filter.AuthenticationFilter.authenticateAndBind(AuthenticationFilter.java:162) ~[obiba-shiro-web-1.8.8.jar:na]
	at org.obiba.shiro.web.filter.AuthenticationFilter.doFilterInternal(AuthenticationFilter.java:130) ~[obiba-shiro-web-1.8.8.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.obiba.agate.config.WebConfiguration$NoTraceFilter.doFilter(WebConfiguration.java:283) [classes/:1.3.1]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:224) [websocket-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [jetty-io-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.18.v20160721.jar:9.2.18.v20160721]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.18.v20160721.jar:9.2.18.v20160721]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
```
The error has been repeating every 7 seconds since it first occurred. It is always the same, except for the session id. I checked `rest.log` and no HTTP requests are being made, though. So it seems that Agate is stuck on a loop somewhere.  

I also noticed that the `$AGATE_HOME/work/ehcache/shiro-active%0053ession%0043ache.data` file had size 0.  

I thought the cache file being empty could be the cause of the error so I tried to reproduce it in another machine by manually emptying the cache file but to no avail. The file is just re-written again when I log in successfully.  

## Workaround
I ended up just restarting Agate and the error was gone. Which was easy enough, but could become a nuisance in a production environment.

**Comment by ymarcon** [comment]
Thanks for the report. Which version of Agate is it?

**Comment by gflcampos** [comment]
Sorry, it's 1.3.0. I have added the version to the description.

**Comment by ymarcon** [comment]
Have you tried with latest version of Agate, i.e. 1.4.1?

**Comment by gflcampos** [comment]
I will try that, thank you. 
Although there is no way of knowing if it fixes this issue other than waiting to see f it happens again...

**Comment by gflcampos** [comment]
It just happened again. So I guess it's not related to the Agate version.
I noticed that none of the registered users are able to log in as well (not just the admin).

**Comment by ymarcon** [comment]
I have released agate 1.4.2 with a fix. As this bug is hard to reproduce, I have strengthen the code to handle such a situation cleanly. Feel free to reopen the issue if it happen again.

**Comment by gflcampos** [comment]
Thank you! We will try version 1.4.2.

**Comment by ymarcon** [comment]
Good. Try the latest (1.4.3). There is also a release of opal (2.13) that would help.

**Comment by gflcampos** [comment]
Sorry to bother you with this again, but the `There is no session with id ...` is still happening...
We installed version 1.4.3 about two weeks ago and everything was fine until yesterday.

I noticed a new [commit](0885be9cb07871c993ca55689a318fd7d9f7625b) from 3 days ago. Is it related to this issue?

**Comment by ymarcon** [comment]
What's the agate.log?

**Comment by meek0** [comment]
I could not reproduce an agate login using a session id but it is a normal occurrence for mica when using the drupal app. Drupal's user will communicate with mica using its session id.

Obiba apps authenticating with agate will do so with the obibaid (using tickets instead because they don't have a session per se in agate).

Mica has not yet released with the obiba-commons' fix. A mica release is to be expected within the week.

**Comment by gflcampos** [comment]
@ymarcon the log is the same as in the initial description. And it still repeats every 7 seconds after it happens the first time.

@meek0 thank you for your answer, I do understand that. But the authentication fails even with the administrator account directly in Agate.

**Comment by ymarcon** [comment]
I am going to try to reproduce the issue by using a script that creates many user sessions.

**Comment by meek0** [comment]
I will try on my end also. 
My setup consists of 5 users where:
* 3 users login once then use the session id for subsequent queries
* 1 user continuously logs in
* 1 user continuously logs in but has a cookie containing its session id

All queries are done in a 2s frequency.

**Comment by ymarcon** [comment]
Just to be sure: have you modified the EhCache configuration (by adding a ehcache.xml file in the conf directory)?

**Comment by ymarcon** [comment]
I have sent 150K requests to Agate directly and no error is reported, agate-shiro cache seems to be growing without limit (>115M).

When sending requests through Mica (dev), after ~2000 calls there is a similar error (no such session) which happens in mica, not in agate. The mica-shiro cache file fells down to 0.

```
Caused by: org.apache.shiro.session.UnknownSessionException: There is no session with id [93c304e4-3143-4e02-88ab-17d7698714eb]
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170)
	at org.apache.shiro.session.mgt.eis.CachingSessionDAO.readSession(CachingSessionDAO.java:261)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249)
	at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141)
	at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
	at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:469)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:153)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipal(DelegatingSubject.java:149)
	at org.obiba.mica.security.ShiroAuditorAware.getCurrentAuditor(ShiroAuditorAware.java:24)
	at org.obiba.mica.web.rest.security.AuditInterceptor.getArguments(AuditInterceptor.java:56)
	at org.obiba.mica.web.rest.security.AuditInterceptor.logServerError(AuditInterceptor.java:83)
	at org.obiba.mica.web.rest.security.AuditInterceptor.filter(AuditInterceptor.java:49)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:196)
```

**Comment by ymarcon** [comment]
I have applied ehcache settings in mica similar to the ones of agate and it works much better, no more "no session with id xxx" errors.

**Comment by gflcampos** [comment]
> Just to be sure: have you modified the EhCache configuration (by adding a ehcache.xml file in the conf directory)?

I have not modified the EhCache configuration.

**Comment by gflcampos** [comment]
> I have applied ehcache settings in mica similar to the ones of agate and it works much better, no more "no session with id xxx" errors. Maybe we should increase the mica defaults.

So, do you think the issue in Agate could be caused by Mica?
Did the "There is no session with id ..." error in Mica also keep repeating in the logs?

**Comment by ymarcon** [comment]
We are able to reproduce the "no session with id" error in mica, and the main difference with agate is the size of the cache. In addition to that I have fixed the configuration of the shiro scheduler that cleans the invalid (=expired) sessions. Agate 1.4.5 has been published.

**Comment by gflcampos** [comment]
OK, thanks! I will try version 1.4.5.
